### ISSUE TITLE
Traceback (most recent call last) issue

### ISSUE THREAD

**Issue by pasqualesimonetti** [sail-sg/sewformer#3]
```
$ python inference.py -c ./configs/test.yaml -d ./assets/data/deepfashion -t deepfashion -o outputs/deepfashion
C:\Developer/sewformer/SewFactory/packages
C:\Developer/sewformer/SewFactory/packages
Traceback (most recent call last):
  File "C:\Developer\sewformer\Sewformer\inference.py", line 138, in <module>
    shape_experiment = ExperimentWrappper(config, system_info['wandb_username'])  # finished experiment
  File "C:\Developer\sewformer\Sewformer\experiment.py", line 39, in __init__
    if config['experiment']['is_training'] and self.run_local_path is not None:
KeyError: 'is_training'
```

**Comment by Mamba-ZJP** [comment]
You need to manually add key `is_training: False' in the config by yourself.

**Comment by Mamba-ZJP** [comment]
You need to manually add key `is_training: False` in the config by yourself.
