### ISSUE TITLE
KeyError: 'is_training'

### ISSUE THREAD

**Issue by nagexiaochengzi** [sail-sg/sewformer#9]
Traceback (most recent call last):
  File "SewFormer/Sewformer/inference.py", line 138, in <module>
    shape_experiment = ExperimentWrappper(config, system_info['wandb_username'])  # finished experiment
  File "SewFormer/Sewformer/experiment.py", line 39, in __init__
    if config['experiment']['is_training'] and self.run_local_path is not None:
KeyError: 'is_training'

**Comment by yukistavailable** [comment]
just modify the code line 39 in SewFormer/Sewformer/experiment.py as following

```
if config['experiment'].get('is_training') and self.run_local_path is not None:
```

**Comment by nagexiaochengzi** [comment]
Where do you realize the reconstruction of garments?
